### ISSUE TITLE
Adjust the height of logo in advanced search page.

### ISSUE THREAD

**Issue by Vivek-Py** [Vivek-Py/Frontend-searchengine#1]
Height of the logo in navbar needs to be fixed as it is stretching.

**Comment by coded1guy** [comment]
hey @Vivek-Py can you assign this issue to me

**Comment by coded1guy** [comment]
@Vivek-Py I don't see any problem with the logo, please can you explain the problem better to me.

**Comment by Vivek-Py** [comment]
The issue has been fixed.
